# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0018_auto_20171208_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('registree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payement', to='admission.Registration')),
            ],
        ),
    ]
