# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_code', models.CharField(max_length=6, verbose_name='Code')),
                ('cr_label', models.CharField(max_length=30, verbose_name='Nom de la classe')),
                ('classroom_add_date', models.DateTimeField(auto_now_add=True)),
                ('classroom_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_add_date', models.DateTimeField(auto_now_add=True)),
                ('course_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_level', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('Licence', (('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'))), ('Masters', (('m1', 'Masters 1'), ('m2', 'Masters 2')))], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admission_fees', models.IntegerField()),
                ('department_add_date', models.DateTimeField(auto_now_add=True)),
                ('department_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departement.Department'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.Department', verbose_name='Departement'),
        ),
    ]
