# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Hacking', max_length=200, unique=True)),
                ('level', models.CharField(choices=[('Licence', (('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'))), ('Masters', (('m1', 'Masters 1'), ('m2', 'Masters 2')))], max_length=7)),
                ('description', models.TextField(default='This Course is Awesome')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Computer Science', max_length=200, unique=True)),
                ('description', models.TextField(default='The best department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departement.Department'),
        ),
    ]
