# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
