# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_auto_20171202_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.CourseLevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='level',
            field=models.CharField(choices=[('Licence', (('lic1', 'Licence 1'), ('lic2', 'Licence 2'), ('lic3', 'Licence 3'))), ('Masters', (('mas1', 'Masters 1'), ('mas2', 'Masters 2')))], max_length=7),
        ),
    ]
