# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_academicyear_school_name'),
        ('departement', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=45, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='fees',
            field=models.IntegerField(default=5655),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(default=55656, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
            preserve_default=False,
        ),
    ]
