# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_department_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='department',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
