# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20180109_1542'),
        ('departement', '0006_auto_20171211_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.ClassLevel', verbose_name='class_subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='course',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='cr_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='cr_label',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='classroom_add_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='classroom_modify_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='department',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseLevel',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.ClassLevel', verbose_name='class_rooms'),
            preserve_default=False,
        ),
    ]
