# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0008_auto_20171031_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cr_code',
            field=models.CharField(max_length=6, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cr_label',
            field=models.CharField(max_length=30, verbose_name='Nom de la classe'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.Department', verbose_name='Departement'),
        ),
    ]
