# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0009_auto_20171102_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
    ]
