# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 00:19
from __future__ import unicode_literals

import apps.admission.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0010_activeacademicyear'),
        ('departement', '0005_courselevel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(default=apps.admission.models.student_number, editable=False, max_length=18, unique=True)),
                ('admission_add_date', models.DateTimeField(auto_now_add=True)),
                ('admission_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('registration_fees_paid', models.DecimalField(decimal_places=2, max_digits=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_process', to='departement.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_number', models.CharField(default=apps.admission.models.registration_number, editable=False, max_length=18, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('id_card_number', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=100, null=True)),
                ('school_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('option', models.CharField(choices=[('sm', 'Sciences Mathématiques'), ('se', 'Sciences Experimentales'), ('ss', 'Sciences Sociales')], max_length=2)),
                ('year_admission_bac', models.CharField(blank=True, max_length=4, null=True)),
                ('pv', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_add_date', models.DateTimeField(auto_now_add=True)),
                ('registration_modify_date', models.DateTimeField(auto_now=True)),
                
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('can_view_content', 'Can see the specified content'),),
            },
        ),
        migrations.AddField(
            model_name='admissionprocess',
            name='registree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Registration'),
        ),
        migrations.AddField(
            model_name='admission',
            name='registry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.Registration'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('email', 'registry_number')]),
        ),
    ]
