# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=100, null=True)),
                ('school_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('student_card', models.CharField(editable=False, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='departement.Department')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('email', 'student_card')]),
        ),
    ]
