# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registry_number',
            field=models.CharField(default=1155, max_length=15),
            preserve_default=False,
        ),
    ]
