# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_courselevel_course'),
        ('school', '0010_activeacademicyear'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='student_images'),
        ),
    ]
