# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_registration_registry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.Registration')),
            ],
        ),
    ]
