# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_courselevel_course'),
        ('admission', '0002_auto_20171203_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.CourseLevel'),
            preserve_default=False,
        ),
    ]
