# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='department',
        ),
    ]
