# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_activeacademicyear'),
        ('admission', '0004_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='active_year',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='school.ActiveAcademicYear'),
            preserve_default=False,
        ),
    ]
