# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_remove_registration_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='option',
            field=models.CharField(choices=[('sm', 'SM'), ('se', 'SE'), ('ss', 'SS')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='year_admission_bac',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
