# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20171029_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='matricule',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='registry_number',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
