# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_registration_active_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='active_year',
            field=models.CharField(max_length=32),
        ),
    ]
