# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20171203_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
