# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20171029_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='id_number',
            new_name='id_card_number',
        ),
    ]
