# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20171203_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['pk'], 'permissions': (('can_view_content', 'Can see the specified content'),)},
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='student_images'),
        ),
    ]
