# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20171030_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
