# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20171030_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='matricule',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
