# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0009_auto_20171205_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
