# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_auto_20171030_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
