# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20171206_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='registree_name',
            field=models.CharField(default='diallo', max_length=50),
            preserve_default=False,
        ),
    ]
