# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_admission_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registry_number',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
