# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_admissionprocess_registree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
