# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_auto_20171030_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
