# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_registration_pv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='admission_date',
            new_name='admission_add_date',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='registration_date',
            new_name='registration_add_date',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
