# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 12:55
from __future__ import unicode_literals

import apps.admission.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0013_admissionprocess_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(default=apps.admission.models.student_number, editable=False, max_length=18, unique=True)),
                ('admission_add_date', models.DateTimeField(auto_now_add=True)),
                ('admission_modify_date', models.DateTimeField(auto_now=True)),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.AdmissionProcess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='admission',
            name='registry',
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
