# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20171031_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='matricule',
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='option',
            field=models.CharField(choices=[('sm', 'Sciences Mathématiques'), ('se', 'Sciences Experimentales'), ('ss', 'Sciences Sociales')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registry_number',
            field=models.CharField(editable=False, max_length=18),
        ),
    ]
