# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20171208_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='admission_denied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionprocess',
            name='admission_denied_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
