# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:10
from __future__ import unicode_literals

import apps.admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20171031_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='matricule',
            field=models.CharField(default=apps.admission.models.student_number, editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='option',
            field=models.CharField(choices=[('sm', 'Sciences Mathématiques'), ('se', 'Sciences Experimentales'), ('ss', 'Sciences Sociales')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registry_number',
            field=models.CharField(default=apps.admission.models.registration_number, editable=False, max_length=18),
        ),
    ]
