# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20171111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='matricule',
            field=models.CharField(editable=False, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registry_number',
            field=models.CharField(editable=False, max_length=18, unique=True),
        ),
    ]
