# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20171208_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionprocess',
            name='admission_denied',
        ),
        migrations.RemoveField(
            model_name='admissionprocess',
            name='admission_denied_date',
        ),
        migrations.RemoveField(
            model_name='admissionprocess',
            name='approved_by_commitee',
        ),
        migrations.AddField(
            model_name='admissionprocess',
            name='commitee_decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=30),
            preserve_default=False,
        ),
    ]
