# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_auto_20171208_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='commitee_decision',
            field=models.CharField(choices=[('approuvé', 'Approuvé'), ('rejecté', 'Rejeté'), ('0', 'Autre')], max_length=30),
        ),
    ]
