# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0010_remove_department_school'),
        ('admission', '0016_auto_20171115_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='department',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='fees',
        )
    ]
