# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20171208_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='commitee_decision',
            field=models.CharField(max_length=30),
        ),
    ]
