# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20171115_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to=' student_images'),
        ),
    ]
