# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0010_remove_department_school'),
        ('admission', '0018_admission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission_process', to='departement.Department'),
            preserve_default=False,
        ),
    ]
