# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_auto_20171209_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='registry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reg_inscription', to='admission.Registration'),
        ),
    ]
