# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_admissionprocess_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': (('can_view_content', 'Can see the specified content'),)},
        ),
    ]
