# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20171118_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='student_images'),
        ),
    ]
