# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20171117_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='payment_date',
            field=models.DateField(help_text='15-06-2017'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(help_text='15-06-2017'),
        ),
    ]
