# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_auto_20171118_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-pk'], 'permissions': (('can_view_content', 'Can see the specified content'),)},
        ),
    ]
