# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_auto_20171117_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='image',
            field=models.ImageField(default='default.png', upload_to=' student_images'),
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
