# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_inscription_active_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=16),
        ),
        migrations.AlterField(
            model_name='registration',
            name='option',
            field=models.CharField(choices=[('mathématique', 'Mathématiques'), ('experimentale', 'Experimentales'), ('sociale', 'Sociales')], max_length=16),
        ),
    ]
