# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_auto_20171211_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='option',
            field=models.CharField(choices=[('mathématique', 'Mathématiques'), ('experimentale', 'Experimentales'), ('sociale', 'Sociales')], max_length=32),
        ),
    ]
