# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_academicyear_school_name'),
        ('admission', '0022_auto_20171118_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.AcademicYear'),
            preserve_default=False,
        ),
    ]
