# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_auto_20171211_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='admission_add_date',
            new_name='inscription_add_date',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='admission_modify_date',
            new_name='inscription_modify_date',
        ),
    ]
