# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_auto_20171117_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='image',
            field=models.ImageField(upload_to='student_images'),
        ),
    ]
