# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0010_remove_department_school'),
        ('admission', '0023_admission_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='departement.ClassRoom'),
            preserve_default=False,
        ),
    ]
