# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_auto_20171212_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='registry',
            new_name='registree',
        ),
    ]
