# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 15:42
from __future__ import unicode_literals

import apps.admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_auto_20171212_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='id_card_number',
            new_name='birth_certificate_number',
        ),
        migrations.RemoveField(
            model_name='admissionprocess',
            name='pass_bac',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='option',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year_admission_bac',
        ),
    ]
