# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20180109_1542'),
        ('departement', '0007_auto_20180109_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='class_level',
            field=models.ForeignKey(default=1, max_length=32, on_delete=django.db.models.deletion.CASCADE, to='departement.ClassLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.ClassLevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='registree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_inscription', to='admission.AdmissionProcess'),
        ),
    ]
