# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_admissionprocess_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='matricule',
            field=models.CharField(default='10', editable=False, max_length=17, unique=True),
        ),
    ]
