# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 12:54
from __future__ import unicode_literals

import apps.admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0029_auto_20180116_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='matricule',
            field=models.CharField(default=apps.admission.models.student_number, editable=False, max_length=18, unique=True),
        ),
    ]
