# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_auto_20180116_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nationality',
            field=models.CharField(max_length=32),
        ),
    ]
