# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0032_auto_20180116_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Guinée', max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_modify_date',
            field=models.DateField(auto_now=True),
        ),
    ]
