# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_remove_registration_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.Country'),
            preserve_default=False,
        ),
    ]
