# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payement', to='admission.AdmissionProcess'),
        ),
    ]
