# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0002_auto_20180118_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fees',
            name='fee_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='payement_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
