# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_abreviation', models.CharField(max_length=10)),
                ('school_slogan', models.CharField(max_length=50)),
                ('adresse_line1', models.CharField(max_length=50)),
                ('adresse_line2', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('autorization', models.CharField(max_length=10)),
                ('registry_number', models.CharField(max_length=10)),
            ],
        ),
    ]
