# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20171023_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='school_name',
        ),
    ]
