# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20171030_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='academicYear_add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='academicYear_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
