# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20171031_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='school_name',
        ),
    ]
