# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_academicyear_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AcademicYear')),
            ],
        ),
    ]
