# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0030_auto_20180116_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_student', to='admission.AdmissionProcess')),
            ],
        ),
        migrations.AddField(
            model_name='payement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payement', to='student.Student'),
        ),
    ]
