# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_activeacademicyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departement', '0007_auto_20180109_1542'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_add_date', models.DateTimeField(auto_now_add=True)),
                ('inscription_modify_date', models.DateTimeField(auto_now=True)),
                ('active_year', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='school.ActiveAcademicYear')),
                ('class_level', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='departement.ClassLevel')),
                ('registree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_inscription', to='student.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
