# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='student',
        ),
        migrations.DeleteModel(
            name='Payement',
        ),
    ]
