# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180118_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='registree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_inscription', to='admission.AdmissionProcess'),
        ),
    ]
